# Generated by Django 5.0.3 on 2024-03-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_magazine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magazine',
            old_name='publishers',
            new_name='critics',
        ),
    ]
